# Tokyo Night Day — Kitty-Farben (generiert)
foreground           #3760bf
background           #e1e2e7
selection_foreground #e1e2e7
selection_background #3760bf

cursor               #3760bf
cursor_text_color    #e1e2e7

url_color            #9854f1

active_border_color   #9854f1
inactive_border_color #8990b3
bell_border_color     #8c6c3e

active_tab_foreground   #c4c8da
active_tab_background   #2e7de9
inactive_tab_foreground #3760bf
inactive_tab_background #d2d4e0
tab_bar_background      #c4c8da

color0  #e9e9ed
color8  #a1a6c5
color1  #f52a65
color9  #f52a65
color2  #587539
color10 #587539
color3  #8c6c3e
color11 #8c6c3e
color4  #2e7de9
color12 #2e7de9
color5  #9854f1
color13 #9854f1
color6  #118c74
color14 #118c74
color7  #6172b0
color15 #3760bf
